services:
  - type: web
    name: stint-backend
    env: node
    region: fra
    buildCommand: npm install && npm run --filter backend build
    startCommand: cd apps/backend && npm run start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

  - type: web
    name: stint-frontend
    env: static
    region: fra
    buildCommand: npm install && npm run --filter frontend build
    staticPublishPath: apps/frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://stint-backend.onrender.com
